name: WINDOWS_TEST_BUILD_ETW

on:
  push:
    branches:
    - main
    - release/*

  pull_request:
    branches:
    - main
    - release/*

jobs:
  validate:
    name: Validate(Windows)
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: 8.0.x

    - name: Build CLOG and run Tests
      run: ./runTests.ps1
      working-directory: ./examples
      shell: pwsh
